### ISSUE TITLE
Fix Asset import in components/index.js

### ISSUE THREAD

**Issue by justTil** [adrianhajdin/brainwave#20]
Hi there, in the readme.md components/index.js file you import ` from "../../public/assets";` in line 37. However, based on the file structure in the YT Video it should be `from "../assets";`. This will cause an error in Header.jsx, because the import in the index.js will not find the assets.

**Comment by MFaisal125** [comment]
my project

**Comment by justTil** [comment]
Has been added in a different issue

**Comment by MFaisal125** [comment]
issue solved
