### ISSUE TITLE
Services.jsx causes some disruption

### ISSUE THREAD

**Issue by Iunezon** [adrianhajdin/brainwave#33]
I don't know why but when I finished the Services section the website suddenly became blank. 
I tried to use different browser, reset pc, delete chunks of code from `Services.jsx`, but situation doesn’t change. 
If I delete `<Services />` and the relative import from `App.jsx` the website comes back to be rendered. 
Did someone encounter the same problem? 
Some solutions please?

**Comment by firegenieuk** [comment]
Usually if you immediately get a blank screen it might be because an import statement is missing or incorrect

**Comment by Iunezon** [comment]
Everything looks fine, I also tried copy-pasting everything Services.jsx from github as well.
